stages:
  - build
  - release
  - deploy

build-helm-package:
  stage: build
  image: alpine/k8s:1.24.12
  rules:
    - changes:
      - momo-store-chart/**/*
  script: 
    - helm package momo-store-chart/
  artifacts:
    paths:
      - momo-store*.tgz
    expire_in: 1 day

release-helm-package:
  stage: release
  rules:
    - changes:
      - momo-store-chart/**/*
  script:
    - curl -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} ${NEXUS_REPO_URL}/momo-store-helm-valerie-shelgunova-diploma/ --upload-file momo-store*.tgz 


apply-helm-package:
  stage: deploy
  image: alpine/k8s:1.24.12
  rules:
    - changes:
      - momo-store-chart/**/*
  script:
    - mkdir ~/.kube/
    - echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config
    - echo "$KUBE_CONFIG" | base64 -d

    - helm repo add momo-store ${NEXUS_REPO_URL}/momo-store-helm-valerie-shelgunova-diploma/ --username ${NEXUS_REPO_USER} --password ${NEXUS_REPO_PASS} 
    - helm repo update 
    - helm upgrade --install momo-store momo-store/momo-store
    
    - rm -f ~/.kube/config
    
  
    


