apiVersion: v2
type: application
name: momo-store
description: Momo Store Helm Chart 

version: 0.0.1
appVersion: "latest"

dependencies:
  - name: backend
    version: 0.0.1
  - name: frontend
    version: 0.0.1
  - name: common_templates
    version: 0.0.1
 
