apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    environment: {{ .Values.global.environment }}
    app: backend
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: momo-store
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.global.backend.replicas }}
  revisionHistoryLimit: 15
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true" 
      labels:
        app: backend
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: backend
          image: {{ .Values.global.backend.image.repository }}:{{ .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.global.backend.imagePullPolicy }}
          ports:
            - name: backend
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 6
      imagePullSecrets:
        - name: docker-config-secret

